name: Print Basic Code

on:
  push:
    branches:
      - main

jobs:
  print_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Basic Code
        run: |
          echo "print('Hello from GitHub Actions!')"
